Update botssh

diff --git a/botssh b/botssh
--- a/botssh
+++ b/botssh
@@ -1,9 +1,10 @@
 #!/bin/bash
 #====================================================
-#	SCRIPT: BOTSSH SSHPLUS MANAGER
-#	DESENVOLVIDO POR:	Noobs
-#	CANAL TELEGRAM:	http://t.me/SWITTECNOLOGIA
+#	SCRIPT: BOT VPN
+#	BASE SCRIPT : By Noob User
+#	CANAL TELEGRAM:	http://t.me/Keting
 #====================================================
+
 clear
 fun_bar() {
     comando[0]="$1"
@@ -35,28 +36,30 @@ fun_bar() {
 fun_botOnOff() {
     [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) = '0' ]] && {
         clear
-        echo -e "\E[44;1;37m             INSTALADOR BOT SSHPLUS                \E[0m\n"
-        echo -ne "\033[1;32mINFORME SEU TOKEN:\033[1;37m "
+        echo -e "\E[44;1;37m             INSTALL BOT VPN                \E[0m\n"
+        echo -ne "\033[1;32mINPUT YOUR BOT TOKEN:\033[1;37m "
         read tokenbot
+
         echo ""
-        echo -ne "\033[1;32mINFORME SEU ID:\033[1;37m "
+        echo -ne "\033[1;32mINPUT YOUR TELEGRAM ID:\033[1;37m "
         read iduser
+
         clear
-        echo -e "\033[1;32mINICIANDO BOT SSHPLUS \033[0m\n"
-        fun_bot1() {
-        	[[ "$(grep -wc '16' /etc/issue.net)" != '0' ]] && {
-        		raw.githubusercontent.com/JeanRocha91x/SSHPLUS/main/Modulos/ShellBot.sh > /etc/SSHPlus/ShellBot.sh
-        	}
-            [[ ! -e "/etc/SSHPlus/ShellBot.sh" ]] && {
-				wget -qO- https://raw.githubusercontent.com/JeanRocha91x/SSHPLUS/main/Modulos/ShellBot.sh >/etc/SSHPlus/ShellBot.sh
-			}
-            cd /etc/SSHPlus
-            screen -dmS bot_plus ./bot $tokenbot $iduser >/dev/null 2>&1
-            [[ $(grep -wc "bot_plus" /etc/autostart) = '0' ]] && {
-                echo -e "ps x | grep 'bot_plus' | grep -v 'grep' || cd /etc/SSHPlus && sudo screen -dmS bot_plus ./bot $tokenbot $iduser && cd $HOME" >>/etc/autostart
-            } || {
-                sed -i '/bot_plus/d' /etc/autostart
-                echo -e "ps x | grep 'bot_plus' | grep -v 'grep' || cd /etc/SSHPlus && sudo screen -dmS bot_plus ./bot $tokenbot $iduser && cd $HOME" >>/etc/autostart
+        echo -e "\033[1;32mINSTALL BOT VPN API \033[0m\n"
+fun_bot1() {
+    [[ "$(grep -wc '16' /etc/issue.net)" != '0' ]] && {
+             raw.githubusercontent.com/Manpokr/Bot/main/bot-api.sh > /etc/SSHPlus/ShellBot.sh
+    }
+    [[ ! -e "/etc/.maAsiss/.Shellbtsss" ]] && {
+	     wget -qO- raw.githubusercontent.com/Manpokr/Bot/main/bot-api.sh >/etc/SSHPlus/ShellBot.sh
+    }
+    cd /etc/SSHPlus
+    screen -dmS bot_run run $tokenbot $iduser >/dev/null 2>&1
+    [[ $(grep -wc "bot_run" /etc/autostart) = '0' ]] && {
+             echo -e "ps x | grep 'bot_run' | grep -v 'grep' || sudo screen -dmS bot_run run $tokenbot $iduser && cd $HOME" >>/etc/autostart
+ } || {
+             sed -i '/bot_run/d' /etc/autostart
+             echo -e "ps x | grep 'bot_run' | grep -v 'grep' || sudo screen -dmS bot_run run $tokenbot $iduser && cd $HOME" >>/etc/autostart
             }
             [[ $(crontab -l | grep -c "verifbot") = '0' ]] && (
                 crontab -l 2>/dev/null
@@ -65,44 +68,44 @@ fun_botOnOff() {
             cd $HOME
         }
         fun_bar 'fun_bot1'
-        [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m BOT SSHPLUS ATIVADO !\033[0m" || echo -e "\n\033[1;31m ERRO! REANALISE SUAS INFORMACOES\033[0m"
+        [[ $(ps x | grep "bot_run" | grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m BOT VPN ACTIVATED !\033[0m" || echo -e "\n\033[1;31m ERROR! INFORMATION NOT VALID\033[0m"
         sleep 2
         menu
     } || {
         clear
-        echo -e "\033[1;32mPARANDO BOT SSHPLUS... \033[0m\n"
+        echo -e "\033[1;32mSTOPPED BOT VPN... \033[0m\n"
         fun_bot2() {
-            screen -r -S "bot_plus" -X quit
+            screen -r -S "bot_run" -X quit
             screen -wipe 1>/dev/null 2>/dev/null
-            [[ $(grep -wc "bot_plus" /etc/autostart) != '0' ]] && {
-                sed -i '/bot_plus/d' /etc/autostart
+            [[ $(grep -wc "bot_run" /etc/autostart) != '0' ]] && {
+                sed -i '/bot_run/d' /etc/autostart
             }
             [[ $(crontab -l | grep -c "verifbot") != '0' ]] && crontab -l | grep -v 'verifbot' | crontab -
             sleep 1
         }
         fun_bar 'fun_bot2'
-        echo -e "\n\033[1;32m \033[1;31mBOT SSHPLUS PARADO! \033[0m"
+        echo -e "\n\033[1;32m \033[1;31mBOT VPN STOPPED! \033[0m"
         sleep 2
         menu
     }
 }
 
 fun_instbot() {
-    echo -e "\E[44;1;37m             INSTALADOR BOT SSHPLUS                \E[0m\n"
-    echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31mATENCAO \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
-    echo -e "\n\033[1;32m1° \033[1;37m- \033[1;33mPELO SEU TELEGRAM ACESSE OS SEGUINTES BOT\033[1;37m:\033[0m"
-    echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33mCRIE O SEU BOT \033[1;31mOPCAO: \033[1;37m/newbot\033[0m"
-    echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@SWITTECNOLOGIA \033[1;33mE PEGUE SEU ID \033[1;31mOPCAO: \033[1;37m/id\033[0m"
+    echo -e "\E[44;1;37m             INSTALLATION BOT VPN                \E[0m\n"
+    echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31mATENSION \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
+    echo -e "\n\033[1;32m1° \033[1;37m- \033[1;33m TELEGRAM ACCESS BOT\033[1;37m:\033[0m"
+    echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33mCREATE YOUR OWN BOT BY\033[1;31mTYPE: \033[1;37m/newbot\033[0m"
+    echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@MissRose_bot \033[1;33mE GET YOUR OWN ID BY \033[1;31mTYPE: \033[1;37m/id\033[0m"
     echo -e "\033[1;31m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣\033[0m"
     echo ""
-    read -p "DESEJA CONTINUAR ? [s/n]: " -e -i s resposta
+    read -p "ENTER CONTINUEW ? [s/n]: " -e -i s resposta
     [[ "$resposta" = 's' ]] && {
         fun_botOnOff
     } || {
-        echo -e "\n\033[1;31mRetornando...\033[0m"
+        echo -e "\n\033[1;31mRETURNING...\033[0m"
         sleep 2
         menu
     }
 }
-[[ -f "/etc/SSHPlus/ShellBot.sh" ]] && fun_botOnOff || fun_instbot
+[[ -f "/etc/.maAsiss/.Shellbtsss" ]] && fun_botOnOff || fun_instbot
 #fim
